# Site settings
name: Cs.Zhang的博客
email: zhangchengsheng1@qq.com
author: CapTor
url: https://captorr.github.io
resume_site: https://captorr.github.io
github: https://github.com/captorr
baseurl: ""  #根目录
description: Tomorrow is another day.
motto: I want something just like this.
banner: 要么躺下睡，要么起来嗨
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 3
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: captorr
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : captorr
